### ISSUE TITLE
使用这个组件必需懒加载？

### ISSUE THREAD

**Issue by Mike-Jia** [cipchk/ngx-umeditor#1]
既然你提供了NPM安装包，为何不让用户直接使用？添加的assets太多了，还要自带一个jquery？依赖的js、css、jquery版本是什么？从哪儿来？
用你自家baidu搜索"ngx-umeditor"直接返回没有结果！！能不能给个git样例工程？或者打包一个也行啊。

**Comment by cipchk** [comment]
`ngx-umeditor` 只是对百度 [UMeditor](http://ueditor.baidu.com/website/umeditor.html) 进行 Angular 封装而已；demo，你可以参考：[demo/src](https://github.com/cipchk/ngx-umeditor/tree/master/demo/src)。

**Comment by Mike-Jia** [comment]
如果提需求是否可以移植一个完整版UMEditor发布到NPM上？现在这个版本的效果还不如直接引入任意一个第三方组件来得简单。
在package.json中写死angular版本为4.0.1，我也觉得很是奇怪。我为了测试这个工具专门把我工程中的包全部修改成4.0.1。。。。。。
其实大部分用户也就希望可以有一个基础的angular2原生富文本工具，如果你的定位只是这样简单包装，我也只有考虑换个其它的了。。

**Comment by cipchk** [comment]
其实是依赖关系的问题，但那也只是警告（换句话说你可以无视这种警告），我会修复它。

另外，我并不会将UMEditor直接移入 `ngx-umeditor` 中，原因是组件一但移入的话，那么会导致整个组件非常大，而组件在使用过程可能并不是一开始就需要用到这个组件。所以懒加载本身是合理的，这一点并不会改变它。
