### ISSUE TITLE
Cannot redeclare block-scoped variable 'ngDevMode'

### ISSUE THREAD

**Issue by minliacom** [cipchk/ngx-umeditor#11]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[X] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce

第一种情况：
在项目中使用package.json里申明式使用时会报 Cannot redeclare block-scoped variable 'ngDevMode'

解决方案：
1. 使用 `npm i --save  "ngx-umeditor"`
2. 删除当前项目下node_modules/ngx-umeditor/node_modules目录

我在这块是一菜鸟， 正在努力学习，不知道有没有专业术语描述此问题， 如有描述不够准确的地方还请多多包含。

感谢作者的努力。

## What is expected?

package.json里引用依赖和通过`npm i --save  "ngx-umeditor"`安装依赖效果一致

## What is actually happening?

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-umeditor/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

**Comment by cipchk** [comment]
angular6 请使用 `2.x`，其他请使用 `1.x`

**Comment by minliacom** [comment]
在ng-alain里面没有重现，不发生这种情况， 但是在typerx里面会存在这个情况， 另angular6 请使用 2.x，其他请使用 1.x 这个是指的什么的版本

**Comment by cipchk** [comment]
```bash
npm i --save ngx-umeditor@^1.0.0
// or
npm i --save ngx-umeditor@^2.0.0
```

**Comment by minliacom** [comment]
是说在2.0.0版本里面已经解决了此问题吗？ 我现在用的是2.0.0版存在这个问题不知道是否正常，奇怪的是在ng-alain项目里加入了同样的"ngx-umeditor": "^2.0.0" 没有报错。新手见谅，浪费您宝贵时间了。

**Comment by cipchk** [comment]
并不是，只是Angular5和6本身是无法兼容的。
