### ISSUE TITLE
插入图片后，选择标题格式后(h1~h6)，把光标停在图片的前面，按下回车后，富文本编辑器就不能编辑了，完全得不到焦点

### ISSUE THREAD

**Issue by ming24** [cipchk/ngx-umeditor#13]
按下回车前：
![rich-text1](https://user-images.githubusercontent.com/9389188/41457549-a1391dec-70b6-11e8-96d7-ee7fd494fa58.png)
按下回车后：
![rich-text2](https://user-images.githubusercontent.com/9389188/41457560-a8c2a15a-70b6-11e8-9280-67b1d427af88.png)

**Comment by cipchk** [comment]
找 umeditor 去
