### ISSUE TITLE
模块都加了为什么还是会出现这样的错误

### ISSUE THREAD

**Issue by zyu** [cipchk/ngx-umeditor#15]
ng:///BizModule/BizBasegoodUpComponent.html@136:48
'umeditor' is not a known element:
1. If 'umeditor' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("tarea highlight-js>&lt;ueditor [(ngModel)]="full_source" #full></ueditor></textarea>

            [ERROR ->]<umeditor [(ngModel)]="full_source" [path]="'./assets/umeditor/'"></umeditor>
        </se>

**Comment by cipchk** [comment]
再细节检查是否加对。
