### ISSUE TITLE
es2015下退出页面调用OnDestroy时候错误

### ISSUE THREAD

**Issue by zhoubonet** [cipchk/ngx-umeditor#19]
![image](https://user-images.githubusercontent.com/4209701/84011140-46769d80-a9a8-11ea-8024-8718aa476215.png)

**Comment by zhoubonet** [comment]
能否修改一下。

**Comment by cipchk** [comment]
@zhoubonet 是否什么错误？

**Comment by zhoubonet** [comment]
map 对象不能够用of 了

**Comment by cipchk** [comment]
你可以在 `polyfills.ts` 中引用 `import 'core-js/features/array/of';`

**Comment by zhoubonet** [comment]
![image](https://user-images.githubusercontent.com/4209701/84111636-f526e680-aa59-11ea-9e25-6cd88bf32421.png)
还是一样了

**Comment by cipchk** [comment]
尝试 `2.0.2` 版本，无须引用 `import 'core-js/features/array/of';`。
