### ISSUE TITLE
再次访问次载入数据失败

### ISSUE THREAD

**Issue by cool1024** [cipchk/ngx-umeditor#2]
组件第一次加载时可以正常显示ngModel的数据，但是一旦离开这个组件所在页面，然后再返回此页面，数据就无法显示了，使用writeValue方法写入数据也没有变化，组件本身可以正常使用，就是无法再通设置方法去改变组件的展示数据了

**Comment by zeject** [comment]
我也遇到了相同的问题

**Comment by cool1024** [comment]
我是直接改源码解决的，在组件理直接引出umeditor对象，进行赋值

**Comment by zeject** [comment]
可以详细说说你的解决方法吗? 谢谢!
` private init(options?: any) {
        this.loading = false;
        if (!window.UM)
            throw new Error('uedito js文件加载失败');

        if (this.instance) return;

        window.UMEDITOR_CONFIG.UMEDITOR_HOME_URL = this.path;
        let umeditor = UM.getEditor(this.id, Object.assign({
            UMEDITOR_HOME_URL: this.path
        }, this.config, options));
        
        umeditor.addListener('ready', () => {
            this.instance = umeditor;
            this.value && this.instance.setContent(this.value);
            this.onReady.emit();
        });
        
        umeditor.addListener('contentChange', () => {
            this.updateValue(umeditor.getContent());
        });
    }`
我查看了源代码,发现是init里面的问题
路由在此进入页面后
this.instance 不存在 但也无法再次触发 ready 事件 ,导致无法赋值

**Comment by cool1024** [comment]
this.onReady.emit();
这里，把umeditor 带出去，然后就能在你的组件代码中直接使用setContent()方法今行设置，这个Umeditor不适合使用ngModel双向绑定，好多BUG，不如在编辑器加载成功的时候直接获取UM对象
@Output() onReady = new EventEmitter<any>();
......
 umeditor.addListener('ready', () => {
        this.instance = umeditor;
        this.value && this.instance.setContent(this.value);
        this.onReady.emit(umeditor);
    });

**Comment by cool1024** [comment]
但是发现图片上传还有跨域问题坑很多，与其搞那么多事情去改，不如自己实现一下哦，自己写个组件引入umeditor,这样来的快

**Comment by cipchk** [comment]
@BeauitfullXiaoJian @zeject 

抱歉，出差一段时间，太忙，把这个 check 给忘记了。

的确是有这个BUG，我已经修复[CHANGELOG](https://github.com/cipchk/ngx-umeditor/blob/master/CHANGELOG.md)。

@zeject 有关于跨域问题，这并不是 `ngx-umeditor` 或 `umeditor` 的问题，有关解决细节，可以自行百度：ueditor 跨域
