### ISSUE TITLE
ngModel的绑定与编辑器改变没有实时双向同步

### ISSUE THREAD

**Issue by lidad** [cipchk/ngx-umeditor#4]
起初文本如下
![_20170914161311](https://user-images.githubusercontent.com/11391332/30419072-b0eb966a-9967-11e7-8a1d-f1e59bd664c0.png)

修改为如下内容
![_20170914161323](https://user-images.githubusercontent.com/11391332/30419079-b4aeed7e-9967-11e7-9e88-ce052ab3d3af.png)

提交之后可以看到提交内容中文本没有发生变化

![_20170914161339](https://user-images.githubusercontent.com/11391332/30419086-b9e652dc-9967-11e7-808b-9fd464825e8c.png)

模板中的代码如下   
`<umeditor [(ngModel)]="formData.content" shark-valid [validFn]="validateContent" name="content" [config]="umeditorOption.config" [path]="umeditorOption.path" #umeditor></umeditor>`

**Comment by cipchk** [comment]
能否以最简的方式呢？比如：

```html
result: {{formData.content}}
<br>
<umeditor [(ngModel)]="formData.content"  name="content"
[config]="umeditorOption.config" [path]="umeditorOption.path" #umeditor></umeditor>
```

观察一下呢？

**Comment by lidad** [comment]
这个样子   

```
<umeditor [(ngModel)]='formData.content' shark-valid [validFn]="validateContent" name="content" [config]="umeditorOption.config" [path]="umeditorOption.path" #umeditor></umeditor>
<p>{{formData.content}}</p>
```

效果是   

![_20170914170440](https://user-images.githubusercontent.com/11391332/30421297-e42d39f0-996e-11e7-84c4-189e0641ed24.png)

**Comment by cipchk** [comment]
抱歉，我无法重现这个问题。我建议你用 `umeditor` 所需要最简化的方式，看是否由于额外的例如 `shark--valid` 指令影响其结果的。

**Comment by lidad** [comment]
好的，这里绑定没有实时，但是使用umeditor的getContent()拿到的东西是修改后的，我也是这样曲线救国了，希望能够帮你查到错

**Comment by cipchk** [comment]
实际上变更是由 UMeditor 的 [contentChange](https://github.com/cipchk/ngx-umeditor/blob/master/src/components/umeditor.component.ts#L79) 事件决定的，`ngx-umeditor` 本身并没有对其进行任何加工，因此我的确很难重现你说的这种问题。

**Comment by cipchk** [comment]
@lidad 我想问一下，你的修改是指如何修改？手动？还是组件类修改 `formData.content` 值？

**Comment by lidad** [comment]
就是修改editor中的内容
