### ISSUE TITLE
编辑器获取到的html代码中的url都被替换成了undefined

### ISSUE THREAD

**Issue by Yonysun** [cipchk/ngx-umeditor#7]
编辑器获取到的html代码中的url都被替换成了undefined
![1](https://user-images.githubusercontent.com/3928873/32878866-b47c95f2-cae2-11e7-9e7a-24c3ad2ef1bd.png)

***********************************************************************

![2](https://user-images.githubusercontent.com/3928873/32878877-bf714da4-cae2-11e7-88f2-fbbadc25aed4.png)

***********************************************************************

![3](https://user-images.githubusercontent.com/3928873/32878881-c463ba86-cae2-11e7-8a5c-4bb3c1eb0b61.png)

`import {Component, EventEmitter, Input, Output, SecurityContext} from '@angular/core';
import {UMeditorComponent} from 'ngx-umeditor';
import {DomSanitizer} from '@angular/platform-browser';

@Component({
    selector: 'app-ng-editor',
    templateUrl: './ng-editor.component.html',
    styleUrls: ['./ng-editor.component.css']
})
export class NgEditorComponent{
    umEditorSourcePath:string = '/assets/plugins/umeditor/';
    @Input() showEditor: boolean = true;
    @Input() showPreview: boolean = true;
    @Input() htmlContent: string = '';
    @Input() editorConfig:object = {
        autoHeightEnabled:false,
    };
    @Output() onContentChanged:EventEmitter<any> = new EventEmitter();
    private UMEditor: UMeditorComponent;

    constructor(private sanitizer: DomSanitizer) {}

    getAllHtml() {
        // 通过 `this.full.Instance` 访问umeditor实例对象
        alert(this.UMEditor.Instance.getAllHtml());
    }

    onUMEditorReady(umEditor:UMeditorComponent) {
        this.UMEditor = umEditor;
        /*console.log(this.htmlContent)*/
        umEditor.Instance.setContent(this.htmlContent,false);
        umEditor.Instance.body.style.height = document.querySelector('.nge-editor')['offsetHeight'] - 100 + "px"
    }

    onUMEditorDestroy($event:any) {
        console.log('onUMEditorDestroy',typeof $event,$event);
    }

    onUMEditorContentChange($event:string) {
        console.log("123",this.UMEditor.Instance.getContent());
        /*this.htmlContent = this.sanitizer.sanitize(SecurityContext.HTML, $event);*/
        this.htmlContent=$event;
        this.onContentChanged.emit($event);
    }
}`

**Comment by cipchk** [comment]
http://www.vephp.com/jiaocheng/125.html
