### ISSUE TITLE
4.1.3版本aot编译时出现不匹配错误

### ISSUE THREAD

**Issue by dllcnx** [cipchk/ngx-umeditor#8]
没有使用官方的脚手架,试着降级了版本也没起作用!
![image](https://user-images.githubusercontent.com/20491834/33756924-ba598e7e-dc32-11e7-805b-5b71102722bb.png)
![image](https://user-images.githubusercontent.com/20491834/33756941-d115021a-dc32-11e7-988e-1ed9df5ca919.png)

**Comment by cipchk** [comment]
duplcated #6

**Comment by dllcnx** [comment]
不知道啥原因,我降级到1.0.4试了试,我直接改json版本号再运行install不起作用,刚刚把所有模块全部删了,重新加载后可以正常编译了,谢谢解答!
