### ISSUE TITLE
Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by vellengs** [cipchk/ngx-umeditor#9]
来回切换  首页和其他页面会产生
```
https://cipchk.github.io/ngx-umeditor/#/ 
```
‘Cannot read property 'nodeType' of undefined’ 错误
 
![207d13e9167e30da20c3b9685aad9778](https://user-images.githubusercontent.com/5743338/36946241-d1a22d10-1ff4-11e8-8b18-8a5eaf6a946b.jpg)

**Comment by xyyang** [comment]
这个问题没有解决吗？

**Comment by cipchk** [comment]
对于快速切换这个问题无法避免，因为组件被销毁后，初始化可能还未完成，所以导致 UMeditor 内部产生错误。
